name: Build and Push Database Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-oracle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Oracle 19c Binary
        run: |
          curl -L -o LINUX.X64_193000_db_home.zip "https://download.oracle.com/otn/linux/oracle19c/190000/LINUX.X64_193000_db_home.zip?AuthParam=1781526612_800c70da26c67ee83c90e230e12b0f71"
          echo "Downloaded file size:"
          ls -lh LINUX.X64_193000_db_home.zip

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Oracle 19c Image
        run: |
          docker build --build-arg SLIMMING=true -t docker.io/pulsarsitra/oracle19c:8-slim .

      - name: Push Oracle 19c Image
        run: |
          docker push docker.io/pulsarsitra/oracle19c:8-slim


      - name: Push PostgreSQL 16 Image
        run: |
          docker push docker.io/pulsarsitra/postgres16:el8
